### ISSUE TITLE
The color of locations panel is wrong

### ISSUE THREAD

**Issue by Gary-Ash** [TheSecEng/Merge-Solarized#1]
<img width="1512" alt="Screen Shot 2022-06-22 at 9 02 06 PM" src="https://user-images.githubusercontent.com/45769603/175185517-9927f101-0055-4c85-9550-afeaf8b60196.png">

**Comment by TheSecEng** [comment]
Thanks ! Will fix tonight.

**Comment by TheSecEng** [comment]
I was never able to reproduce this. I did make minor edits which may or may not impact this

**Comment by TheSecEng** [comment]
NVM just reproduced it!

**Comment by TheSecEng** [comment]
Fixed
